import { NextRequest, NextResponse } from "next/server";
import connectToDB from "@/lib/db/connect";
import Achievement from "@/lib/models/Achievement";

const achievements = [
  // ===== Exchange Master (Mistrz Wymian) =====
  {
    id: "exchange_master_bronze",
    seriesId: "exchange_master",
    seriesName: "Mistrz Wymian",
    name: "Pierwszy Tom w Obiegu",
    description:
      "Każdy mistrz zaczyna od jednego tomu - ten właśnie znalazł nowego właściciela",
    icon: "📖",
    tier: "bronze",
    category: "trading",
    points: 10,
    requirement: { completedTransactions: 1 },
  },
  {
    id: "exchange_master_silver",
    seriesId: "exchange_master",
    seriesName: "Mistrz Wymian",
    name: "Ręka Kupca",
    description: "Twoje transakcje stają się pewne jak Twój uścisk dłoni",
    icon: "🤝",
    tier: "silver",
    category: "trading",
    points: 25,
    requirement: { completedTransactions: 5 },
  },
  {
    id: "exchange_master_gold",
    seriesId: "exchange_master",
    seriesName: "Mistrz Wymian",
    name: "Doświadczony Handlarz",
    description:
      "Znasz już wartość księgi - nie każdy potrafi handlować z honorem",
    icon: "⚖️",
    tier: "gold",
    category: "trading",
    points: 50,
    requirement: { completedTransactions: 25 },
  },
  {
    id: "exchange_master_platinum",
    seriesId: "exchange_master",
    seriesName: "Mistrz Wymian",
    name: "Legenda Wymian",
    description:
      "Opowiadają o tobie legendy - podobno potrafisz wymienić atrament na złoto",
    icon: "👑",
    tier: "platinum",
    category: "trading",
    points: 100,
    requirement: { completedTransactions: 100 },
  },

  // ===== Trusted Trader (Zaufany Handlarz) =====
  {
    id: "trusted_trader_bronze",
    seriesId: "trusted_trader",
    seriesName: "Zaufany Handlarz",
    name: "Godny Zaufania",
    description:
      "Twoje imię pojawia się na ustach kupców - i to w pozytywnych kuluarach",
    icon: "✅",
    tier: "bronze",
    category: "reputation",
    points: 10,
    requirement: { positiveReviews: 5 },
  },
  {
    id: "trusted_trader_silver",
    seriesId: "trusted_trader",
    seriesName: "Zaufany Handlarz",
    name: "Ceniony Antykwariusz",
    description: "Ponoć potrafisz znaleźć tomy, o których zapomniał sam czas",
    icon: "📚",
    tier: "silver",
    category: "reputation",
    points: 25,
    requirement: { positiveReviews: 25 },
  },
  {
    id: "trusted_trader_gold",
    seriesId: "trusted_trader",
    seriesName: "Zaufany Handlarz",
    name: "Sława na Szlaku",
    description: "Podróżni witają cię jak starego przyjaciela",
    icon: "🌟",
    tier: "gold",
    category: "reputation",
    points: 50,
    requirement: { positiveReviews: 50 },
  },
  {
    id: "trusted_trader_platinum",
    seriesId: "trusted_trader",
    seriesName: "Zaufany Handlarz",
    name: "Ikona Salonów",
    description: "Twoja reputacja wyprzedza cię o parę kroków przyjacielu",
    icon: "💎",
    tier: "platinum",
    category: "reputation",
    points: 100,
    requirement: { positiveReviews: 100 },
  },

  // ===== Perfect Rating (Perfekcyjna Ocena) =====
  {
    id: "perfect_rating_bronze",
    seriesId: "perfect_rating",
    seriesName: "Perfekcyjna Ocena",
    name: "Perfekcyjny Sprzedawca",
    description: "Transakcje kończą się uśmiechem - nie tylko twoim :)",
    icon: "😊",
    tier: "bronze",
    category: "reputation",
    points: 15,
    requirement: { averageRating: 5.0, minReviews: 5 },
  },
  {
    id: "perfect_rating_silver",
    seriesId: "perfect_rating",
    seriesName: "Perfekcyjna Ocena",
    name: "Słowo jak Pieczęć",
    description: "Obietnica raz dana trwa wiecznie",
    icon: "🔏",
    tier: "silver",
    category: "reputation",
    points: 30,
    requirement: { averageRating: 5.0, minReviews: 15 },
  },
  {
    id: "perfect_rating_gold",
    seriesId: "perfect_rating",
    seriesName: "Perfekcyjna Ocena",
    name: "Złota Miara",
    description: "Wśród mistrzów Twoje rzemiosło mierzy się w karatach",
    icon: "⭐",
    tier: "gold",
    category: "reputation",
    points: 60,
    requirement: { averageRating: 5.0, minReviews: 50 },
  },
  {
    id: "perfect_rating_platinum",
    seriesId: "perfect_rating",
    seriesName: "Perfekcyjna Ocena",
    name: "Wzór Doskonałości",
    description:
      "Twoje imię zapisano w księdze ideałów - mało kto się tam znajduje. Gratulujemy.",
    icon: "🏆",
    tier: "platinum",
    category: "reputation",
    points: 120,
    requirement: { averageRating: 5.0, minReviews: 100 },
  },

  // ===== Book Collector (Kolekcjoner Książek) =====
  {
    id: "book_collector_bronze",
    seriesId: "book_collector",
    seriesName: "Kolekcjoner Książek",
    name: "Pierwszy Zakurzony Tom",
    description: "Zawsze gdzieś jest początek",
    icon: "📕",
    tier: "bronze",
    category: "collection",
    points: 5,
    requirement: { totalBooksAdded: 5 },
  },
  {
    id: "book_collector_silver",
    seriesId: "book_collector",
    seriesName: "Kolekcjoner Książek",
    name: "Opiekun Półek",
    description: "Zbiory rosną, a kurz zaczyna szeptać opowieści o właścicielu",
    icon: "📚",
    tier: "silver",
    category: "collection",
    points: 20,
    requirement: { totalBooksAdded: 25 },
  },
  {
    id: "book_collector_gold",
    seriesId: "book_collector",
    seriesName: "Kolekcjoner Książek",
    name: "Architekt Biblioteki",
    description: "Budujesz miejsce, w którym każda książka znajdzie dach",
    icon: "🏛️",
    tier: "gold",
    category: "collection",
    points: 40,
    requirement: { totalBooksAdded: 100 },
  },
  {
    id: "book_collector_platinum",
    seriesId: "book_collector",
    seriesName: "Kolekcjoner Książek",
    name: "Strażnik Wiedzy",
    description: "W Twoich regałach ukryte są sekrety dawnych mistrzów",
    icon: "🗝️",
    tier: "platinum",
    category: "collection",
    points: 80,
    requirement: { totalBooksAdded: 250 },
  },

  // ===== Social Butterfly (Towarzyski Motyl) =====
  {
    id: "social_butterfly_bronze",
    seriesId: "social_butterfly",
    seriesName: "Towarzyski Motyl",
    name: "Towarzysz Rozmów",
    description: "Każdy lubi dobrą historię",
    icon: "💬",
    tier: "bronze",
    category: "community",
    points: 5,
    requirement: { conversationsStarted: 5 },
  },
  {
    id: "social_butterfly_silver",
    seriesId: "social_butterfly",
    seriesName: "Towarzyski Motyl",
    name: "Łącznik Społeczności",
    description: "Łączysz ludzi jak most nad doliną pomysłów",
    icon: "🌉",
    tier: "silver",
    category: "community",
    points: 20,
    requirement: { conversationsStarted: 25 },
  },
  {
    id: "social_butterfly_gold",
    seriesId: "social_butterfly",
    seriesName: "Towarzyski Motyl",
    name: "Serce Obozu",
    description:
      "Wokół Ciebie gromadzą się inni by wymieniać opowieści przy ognisku",
    icon: "🔥",
    tier: "gold",
    category: "community",
    points: 40,
    requirement: { conversationsStarted: 100 },
  },
  {
    id: "social_butterfly_platinum",
    seriesId: "social_butterfly",
    seriesName: "Towarzyski Motyl",
    name: "Ambasador",
    description: "Twoje imię otwiera drzwi szybciej niż jakikolwiek klucz",
    icon: "🗝️",
    tier: "platinum",
    category: "community",
    points: 80,
    requirement: { conversationsStarted: 250 },
  },

  // ===== Generous Giver (Hojny Dawca) =====
  {
    id: "generous_giver_bronze",
    seriesId: "generous_giver",
    seriesName: "Hojny Dawca",
    name: "Hojny Debiut",
    description: "Najmniejszy dar zostawia trwalszy ślad niż złoto",
    icon: "🎁",
    tier: "bronze",
    category: "community",
    points: 10,
    requirement: { freeGiveaways: 1 },
  },
  {
    id: "generous_giver_silver",
    seriesId: "generous_giver",
    seriesName: "Hojny Dawca",
    name: "Filantrop z Doliny",
    description: "Hojność rozbrzmiewa echem wśród wzgórz",
    icon: "🌄",
    tier: "silver",
    category: "community",
    points: 30,
    requirement: { freeGiveaways: 5 },
  },
  {
    id: "generous_giver_gold",
    seriesId: "generous_giver",
    seriesName: "Hojny Dawca",
    name: "Mecenas Literatury",
    description: "Twoje wsparcie zaczyna stawać się nieocenione",
    icon: "📜",
    tier: "gold",
    category: "community",
    points: 60,
    requirement: { freeGiveaways: 20 },
  },
  {
    id: "generous_giver_platinum",
    seriesId: "generous_giver",
    seriesName: "Hojny Dawca",
    name: "Święty Zapisów",
    description: "Niektórzy modlą się o mądrość, ty po prostu ją rozdajesz",
    icon: "🕊️",
    tier: "platinum",
    category: "community",
    points: 120,
    requirement: { freeGiveaways: 50 },
  },

  // ===== Thoughtful Reviewer (Wnikliwy Recenzent) =====
  {
    id: "thoughtful_reviewer_bronze",
    seriesId: "thoughtful_reviewer",
    seriesName: "Wnikliwy Recenzent",
    name: "Uważny Skryba",
    description: "Twoje słowa ważą więcej niż niejedna księga, którą oceniasz",
    icon: "✍️",
    tier: "bronze",
    category: "community",
    points: 5,
    requirement: { detailedReviews: 5 },
  },
  {
    id: "thoughtful_reviewer_silver",
    seriesId: "thoughtful_reviewer",
    seriesName: "Wnikliwy Recenzent",
    name: "Kronikarz Zdarzeń",
    description:
      "Zapisujesz historie tak, że inni czują jakby sami w nich uczestniczyli",
    icon: "📖",
    tier: "silver",
    category: "community",
    points: 20,
    requirement: { detailedReviews: 25 },
  },
  {
    id: "thoughtful_reviewer_gold",
    seriesId: "thoughtful_reviewer",
    seriesName: "Wnikliwy Recenzent",
    name: "Krytyk Literacki",
    description:
      "Twoje recenzje potrafią podnieść lub złamać autorskie serca - delikatnie, lecz celnie",
    icon: "🎭",
    tier: "gold",
    category: "community",
    points: 40,
    requirement: { detailedReviews: 100 },
  },
  {
    id: "thoughtful_reviewer_platinum",
    seriesId: "thoughtful_reviewer",
    seriesName: "Wnikliwy Recenzent",
    name: "Guru Opinii",
    description:
      "Nawet mędrcy pytają cię o zdanie, zanim postawią kropkę na końcu zdania",
    icon: "🧙",
    tier: "platinum",
    category: "community",
    points: 80,
    requirement: { detailedReviews: 250 },
  },

  // ===== Loyal Member (Lojalny Członek) =====
  {
    id: "loyal_member_bronze",
    seriesId: "loyal_member",
    seriesName: "Lojalny Członek",
    name: "Siedem Dni na Szlaku",
    description: "Tydzień to dopiero początek wędrówki - ale znasz już drogę",
    icon: "🗺️",
    tier: "bronze",
    category: "activity",
    points: 10,
    requirement: { loginStreak: 7 },
  },
  {
    id: "loyal_member_silver",
    seriesId: "loyal_member",
    seriesName: "Lojalny Członek",
    name: "Miesiąc Podróżnika",
    description: "Słońce wschodzi, księżyć gaśnie, a ty wciąż tu jesteś",
    icon: "🌙",
    tier: "silver",
    category: "activity",
    points: 30,
    requirement: { loginStreak: 30 },
  },
  {
    id: "loyal_member_gold",
    seriesId: "loyal_member",
    seriesName: "Lojalny Członek",
    name: "Nieśmiertelny Czytelnik",
    description:
      "Nie ma takiej nocy, która zatrzymałaby cię przed kolejnym rozdziałem",
    icon: "📚",
    tier: "gold",
    category: "activity",
    points: 60,
    requirement: { loginStreak: 100 },
  },
  {
    id: "loyal_member_platinum",
    seriesId: "loyal_member",
    seriesName: "Lojalny Członek",
    name: "Rok Kronik",
    description: "Twoja obecność została zapisana w gwiazdach",
    icon: "⭐",
    tier: "platinum",
    category: "activity",
    points: 120,
    requirement: { loginStreak: 365 },
  },

  // ===== SPECIAL: Single Achievement (bez serii) =====
  {
    id: "pioneer",
    seriesId: "pioneer",
    seriesName: "Pionier",
    name: "Pionier",
    description: "Byłeś tu zanim pojawiły się mapy",
    icon: "🚩",
    tier: "platinum",
    category: "special",
    points: 150,
    requirement: { joinedBefore: "2025-12-01" },
  },

  // ===== SPECIAL: Seasonal =====
  {
    id: "summer_harvest",
    seriesId: "summer_harvest",
    seriesName: "Letnie Zbiory",
    name: "Letnie Zbiory",
    description:
      "Lato przynosi owoce i nowe tomy, a twoje półki uginają się pod nimi",
    icon: "☀️",
    tier: "gold",
    category: "special",
    points: 50,
    requirement: { exchangesInSummer: 10 },
  },
  {
    id: "new_year_contract",
    seriesId: "new_year_contract",
    seriesName: "Noworoczny Kontrakt",
    name: "Noworoczny Kontrakt",
    description:
      "Nowy rok, nowy handel, niech ten będzie nawet lepszy od poprzedniego! Wesołego Nowego Roku!",
    icon: "🎆",
    tier: "gold",
    category: "special",
    points: 50,
    requirement: { exchangeOnNewYear: true },
  },

  // ===== SPECIAL: Milestone =====
  {
    id: "king_of_merchant_guild",
    seriesId: "king_of_merchant_guild",
    seriesName: "Król Gildii Kupieckiej",
    name: "Król Gildii Kupieckiej",
    description:
      "Należy Ci się pokłon - twoje transakcje przeszły do statusu legendy",
    icon: "👑",
    tier: "platinum",
    category: "special",
    points: 200,
    requirement: { totalPoints: 10000 },
  },
  {
    id: "best_of_the_best",
    seriesId: "best_of_the_best",
    seriesName: "Najlepszy z Najlepszych",
    name: "Najlepszy z Najlepszych",
    description:
      "Osiągnąłeś poziom, o którym inni mogą przeczytać jedynie w bajkach",
    icon: "🌟",
    tier: "platinum",
    category: "special",
    points: 300,
    requirement: { rankingPosition: 1, rankingDays: 30 },
  },
];

export async function POST(req: NextRequest) {
  try {
    await connectToDB();

    await Achievement.deleteMany({});
    await Achievement.insertMany(achievements);

    return NextResponse.json({
      message: "Achievements seeded successfully",
      count: achievements.length,
    });
  } catch (error) {
    console.error("Error seeding achievements:", error);
    return NextResponse.json(
      { error: "Failed to seed achievements" },
      { status: 500 }
    );
  }
}
